src/app/base/__init__.py
from flask import Blueprint

# Define the blueprint: 'base', set its url prefix: app.url/base
base_bp = Blueprint(
    'base',
    __name__,
    url_prefix='/'
)

src/app/base/routes.py
from flask import send_from_directory, abort
import os
import json
import time
import requests
import io
from datetime import datetime
from VERSION import VERSION
from flask import render_template, redirect, request, url_for, abort, Blueprint, flash, send_file, jsonify, current_app, g
from flask_babel import get_locale
from flask_security import Security, SQLAlchemySessionUserDatastore, roles_accepted, login_required, current_user, permissions_required, user_authenticated
from app import uploaded_images
from sqlalchemy import desc, and_, not_, func
from app.models import User, Hotspot, Mediapage, Tour, SharedTour, SharedGroupTour, Asset, Group, GroupUsers, Role, Dependencies, EscapeRoomAnswers, HotspotVisited
from app.base import base_bp
from app import home, db, app, user_datastore
from werkzeug.utils import secure_filename
from app.utils.xapi import lrs_event
from alembic.config import Config
from alembic import command

path_to_static = os.path.join(os.path.join(os.getcwd(), "app"), "static")
path_to_node_modules = os.path.join(os.getcwd(), "node_modules")


@base_bp.before_request
def require_login():
    g.locale = str(get_locale())
    g.locales = os.getenv('LANGUAGES').split(",")
    """Ensure the user is logged in"""
    if request.path.startswith('/home') and not current_user.is_authenticated:
        return redirect(url_for('auth.login', email=request.args.get('email'), token=request.args.get('token')))


@base_bp.route('/', endpoint='index')
def index():
    """
    this function shows the index page depending on the login of a user
    """
    user_id = current_user.id if current_user.is_authenticated else None
    lrs_event('/')
    if (user_id):
        return redirect(url_for('home.home_page', email=request.args.get('email'), token=request.args.get('token')))
    else:
        return render_template('index.html', currentYear=datetime.now().year, VERSION=VERSION)


@base_bp.route('/node_modules/<path:filename>', endpoint='node_modules')
def node_modules(filename):
    return send_from_directory(path_to_node_modules, filename)


@base_bp.route('/uploaded_files/<filename>', methods=['GET', 'POST'], endpoint='serve_uploaded_file')
def serve_uploaded_file(filename):
    """
    this function serves files from /app/Uploaded_Media to the user
    """
    asset_url = f"http://{app.config['ASSET_URL']}/{filename}"

    # start_time = time.monotonic()
    response = requests.get(asset_url, stream=True)
    # end_time = time.monotonic()
    # elapsed_time = end_time - start_time
    # print(f"Time taken for request: {elapsed_time:.2f} seconds")

    lrs_event('/uploaded_files/<filename>')
    return send_file(
        io.BytesIO(response.content),
        mimetype=response.headers.get('content-type'),
        as_attachment=False,
        download_name=filename
    )


@base_bp.route('/uploaded_files/thumbnails/<filename>', methods=['GET', 'POST'], endpoint='serve_uploaded_thumbnails')
def serve_uploaded_thumbnails(filename):
    """
    this function serves files like serve_uploaded_file() but from the thumbnails folder
    """
    return serve_uploaded_file(f"thumbnails/{filename}")


@base_bp.route('/get_hotspot', methods=['POST'], endpoint='get_hotspot')
def get_hotspot():
    """
    this function returns all Hotspots which belongs to a Mediapage but also requires the tour_id
    """
    hotspot = Hotspot.query.get(request.get_json())
    lrs_event('/get_hotspot')
    return jsonify(hotspot.to_dict())


@base_bp.route('/get_hotspots', methods=['POST'], endpoint='get_hotspots')
def get_hotspots():
    """
    this function returns Hotspot which belongs to a Mediapage but also requires the tour_id
    """
    data = request.get_json()
    tour_id = data.get('tour_id')
    mediapage_id = data.get('mediapage_id')

    if not tour_id or not mediapage_id:
        return render_template("error.html", status_code=400, status_message="Tour or Mediapage not found")

    hotspots = Hotspot.query.filter_by(media_page_id=mediapage_id).all()
    hotspots_list = [hotspot.to_dict() for hotspot in hotspots]

    lrs_event('/get_hotspots')
    return jsonify(hotspots_list)


@base_bp.route('/get_mediapages', methods=['POST'], endpoint='get_mediapages')
def get_mediapages():
    """
    this function returns all Mediapages which belongs to a Tour
    """
    data = request.get_json()
    tour_id = data.get('tour_id')

    if not tour_id:
        return render_template("error.html", status_code=400, status_message="Tour not found")

    mediapages = Mediapage.query.filter_by(tour_id=tour_id).all()
    mediapages_list = [mediapage.to_dict() for mediapage in mediapages]

    lrs_event('/get_Mediapages')
    return jsonify(mediapages_list)


@base_bp.route('/view_tour/<int:id>', endpoint='view_tour')
def view_tour(id, share_link=False, full_preload=False):
    """
    this function calls get_hotspots() but from a different route
    """
    if share_link:
        # Retrieve tour by share string
        tour = Tour.query.filter_by(share_string=id).first()
    else:
        if not current_user.is_authenticated:
            return redirect(url_for('auth.login', email=request.args.get('email'), token=request.args.get('token'), view_tour=id))

        # Retrieve tour by id and creator_id
        tour = Tour.query.filter_by(id=id, creator_id=current_user.id).first()
        if current_user.has_permission('user_management'):
            tour = Tour.query.filter_by(id=id).first()

        # Check if the tour is shared with the current user or one of the user's groups
        if not tour:
            shared_tour = SharedTour.query.filter_by(
                tour_id=id, collaborator_id=current_user.id).first()
            shared_group_tour = SharedGroupTour.query.join(GroupUsers, GroupUsers.group_id == SharedGroupTour.group_id).filter(
                SharedGroupTour.tour_id == id, GroupUsers.user_id == current_user.id).first()
            if shared_tour or shared_group_tour:
                tour = Tour.query.filter_by(id=id).first()
            else:
                if current_user.is_authenticated and Tour.query.filter_by(id=id).first():
                    return render_template("error.html", status_code=403, status_message="Access denied")
                else:
                    return render_template("error.html", status_code=404, status_message="Tour not found")

    # Retrieve all mediapages and hotspots associated with the tour
    mediapages = Mediapage.query.filter_by(tour_id=tour.id).all()
    # hotspots = Hotspot.query.join(Mediapage, and_(
    #    Hotspot.media_page_id == Mediapage.id, Mediapage.tour_id == tour.id)).all()
    mediapages_dicts = [mediapage.to_dict() for mediapage in mediapages]
    """ hotspots = Hotspot.query.add_column(func.group_concat(Dependencies.dependsOn).label('dependencies'))
    hotspots = hotspots.join(Mediapage, and_(Hotspot.media_page_id == Mediapage.id, Mediapage.tour_id == tour.id))
    hotspots = hotspots.join(Dependencies, Hotspot.id == Dependencies.hotspot_id, isouter=True).group_by(Hotspot.id).all()
    
    hotspots_dicts = [{ **hotspot[0].to_dict(), "dependencies": [int(x) for x in hotspot[1].split(',')] if hotspot[1] else []} for hotspot in hotspots] """

    # [ { hotspot_id: 2, dependencies: [3, 4, 5] }, .... ]
    # currentSession = Sessions.query.filter_by(user_id=current_user.id , tour_id = tour.id).all()
    # add HotpotVisited to mediapages_dicts
    if current_user.is_authenticated:
        for mediapage in mediapages_dicts:
            for hotspot in mediapage["hotspots"]:
                hotspot["visited"] = HotspotVisited.query.filter_by(
                    user_id=current_user.id, hotspot_id=hotspot["id"]).first() is not None

    lrs_event('/view_tour/<int:id>')
    return render_template('view_tour.html', tour_id=tour.id, mediapages=mediapages_dicts,
                           mediatypes='mediatypes_dict', currentYear=datetime.now().year, full_preload=full_preload, VERSION=VERSION)


@base_bp.route('/view/<string:id>', endpoint='view_tour_by_sharestring')
def view_tour_by_sharestring(id):
    """
    this function does the same as view_tour but no login is required because the share-string was used
    """
    return view_tour(id, share_link=True)


@base_bp.route('/view_offline/<string:id>', endpoint='view_tour_fully_preloaded')
def view_tour_fully_preloaded(id):
    """
    this function does the same as view_tour but all assets get preloaded in the beginning
    """
    return view_tour(id, full_preload=True)


@base_bp.route('/setHotspotReset', methods=['POST'])
def setHotspotReset():
    data = request.get_json()
    tour_id = data.get('tour_id')
    hotspotVisitedArray = HotspotVisited.query.filter_by(
        user_id=current_user.id, tour_id=tour_id).all()
    for hotVis in hotspotVisitedArray:
        db.session.delete(hotVis)
        db.session.commit()
    return jsonify({'message': 'Hotspot reset successfully'})


@base_bp.route('/visitedHotspot', methods=['POST'])
def visitedHotspot():
    data = request.get_json()
    id = data.get('id')
    tour_id = data.get('_tour_id')
    print(id)
    print(tour_id)

    existingHotspotVisited = HotspotVisited.query.filter_by(
        hotspot_id=id, user_id=current_user.id, tour_id=tour_id).first()
    if not existingHotspotVisited:
        newHotspotVisited = HotspotVisited(
            user_id=current_user.id, hotspot_id=id, tour_id=tour_id)
        db.session.add(newHotspotVisited)
        db.session.commit()

    ready_hotspots = []

    # dependent hotspots
    possHotspots = Dependencies.query.filter(
        Dependencies.dependsOn == id).all()

    for hot in possHotspots:
        possible = True
        depends = Dependencies.query.filter(
            Dependencies.hotspot_id == hot.hotspot_id).all()
        for dep in depends:

            dephot = HotspotVisited.query.filter_by(
                hotspot_id=dep.dependsOn, user_id=current_user.id, tour_id=tour_id).first()
            if not dephot:

src/app/templates/base.html
<!doctype html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- CSS -->
    <link
      href="{{ url_for('static', filename='css/base_style.css') }}"
      rel="stylesheet"
    />
    <link
      href="{{ url_for('static', filename='../node_modules/vanilla-cookieconsent/dist/cookieconsent.css') }}"
      rel="stylesheet"
    />
    {% block add_to_head %}{% endblock %}
    <title>{{ _("19squared - Just more than 360") }}</title>
    <link
      rel="icon"
      type="image/png"
      href="{{ url_for('static', filename='img/brand/favicon.png') }}"
    />
    <link
      rel="icon"
      href="{{ url_for('static', filename='img/brand/favicon.ico') }}"
    />
    <link
      rel="manifest"
      href="{{ url_for('static', filename='manifest.json') }}"
    />
  </head>
  <body>
    <script src="{{ url_for('static', filename='../node_modules/aframe/dist/aframe-v1.6.0.min.js') }}"></script>
    <script src="{{ url_for('static', filename='../node_modules/jquery/dist/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='../node_modules/bootstrap/dist/js/bootstrap.bundle.min.js') }}"></script>
    <script src="{{ url_for('static', filename='../node_modules/socket.io/client-dist/socket.io.min.js') }}"></script>
    <script
      type="module"
      src="{{ url_for('static', filename='cookieconsent-config.js') }}"
    ></script>

    <div class="vh-100 d-flex flex-column justify-content-between">
      <div class="page-wrapper">
        <header
          class="noselect"
          style="box-shadow: 0px 5px 10px #2d3436; min-width: 100%;"
        >
          <nav class="navigation navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
              <a class="navbar-brand" href="{{ url_for('base.index') }}">
                <img
                  src="{{ url_for('static', filename='img/brand/banner1.png') }}"
                  alt="19squared"
                  height="55px"
                  style="margin-left: 4px"
                />
              </a>
              {% if request.host.startswith('stage') %}
                <span class="text-light">{{ _("Staging Environment") }}</span>
              {%
                  elif request.host.startswith('127.0.0.1') or
                  request.host.startswith('localhosts')
                %}
                <span class="text-light">{{ _("Local Development") }}</span>
              {% endif %}
              <button
                class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarNav"
                aria-controls="navbarNav"
                aria-expanded="false"
                aria-label="Toggle navigation"
              >
                <span class="navbar-toggler-icon"></span>
              </button>

              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                  {% if current_user.is_authenticated %}
                    <li class="nav-item">
                      {% if request.endpoint == "home.home_page" %}
                        <a
                          class="nav-link text-light"
                          href="{{ url_for('base.index') }}"
                        >
                          {{ _("Home") }}
                        </a>
                      {% else %}
                        <a class="nav-link" href="{{ url_for('base.index') }}">
                          {{ _("Home") }}
                        </a>
                      {% endif %}
                    </li>
                    {%
                      if
                      current_user.has_permission('edit_group')
                    %}
                      <li class="nav-item">
                        {% if request.endpoint == "home.groups" %}
                          <a
                            class="nav-link text-light"
                            href="{{ url_for('home.groups') }}"
                          >
                            {{ _("Groups") }}
                          </a>
                        {% else %}
                          <a
                            class="nav-link"
                            href="{{ url_for('home.groups') }}"
                          >
                            {{ _("Groups") }}
                          </a>
                        {% endif %}
                      </li>
                    {% endif %}
                    {%
                      if
                      current_user.has_permission('user_management')
                    %}
                      <li class="nav-item">
                        {% if request.endpoint == "home.user_management" %}
                          <a
                            class="nav-link text-light"
                            href="{{ url_for('home.user_management') }}"
                            >{{ _("User-Management") }}</a
                          >
                        {% else %}
                          <a
                            class="nav-link"
                            href="{{ url_for('home.user_management') }}"
                            >{{ _("User-Management") }}</a
                          >
                        {% endif %}
                      </li>
                    {% endif %}
                    <li class="nav-item">
                      {% if request.endpoint == "home.profil" %}
                        <a
                          class="nav-link text-light"
                          href="{{ url_for('home.profil') }}"
                          >{{ current_user.username }}</a
                        >
                      {% else %}
                        <a class="nav-link" href="{{ url_for('home.profil') }}"
                          >{{ current_user.username }}</a
                        >
                      {% endif %}
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{{ url_for('auth.logout') }}"
                        >{{ _("Logout") }}</a
                      >
                    </li>
                  {% else %}
                    <li class="nav-item">
                      {% if request.endpoint == "auth.login" %}
                        <a
                          class="nav-link text-light"
                          href="{{ url_for('auth.login') }}"
                          >{{ _("Login") }}</a
                        >
                      {% else %}
                        <a class="nav-link" href="{{ url_for('auth.login') }}"
                          >{{ _("Login") }}</a
                        >
                      {% endif %}
                    </li>
                    <li class="nav-item">
                      {% if request.endpoint == "auth.register" %}
                        <a
                          class="nav-link text-light"
                          href="{{ url_for('auth.register') }}"
                          >{{ _("Register") }}</a
                        >
                      {% else %}
                        <a
                          class="nav-link"
                          href="{{ url_for('auth.register') }}"
                          >{{ _("Register") }}</a
                        >
                      {% endif %}
                    </li>
                  {% endif %}
                </ul>
              </div>
            </div>
          </nav>
        </header>
        {% block content_fullPage %}
          <main class="container mt-5">{% block content %}{% endblock %}</main>
        {% endblock %}
      </div>
      <footer
        class="navigation text-white d-flex justify-content-between p-3 flex-wrap justify-content-between align-items-center noselect"
        style="box-shadow: 0px -5px 10px #2d3436; min-width: 100%"
      >
        <div clas="col-md-4 p-2">
          <a
            class="link-light text-decoration-none"
            href="/impressum"
            style="margin-right: 10px"
            >{{ _("Impressum") }}</a
          >
          <a class="link-light text-decoration-none" href="/datenschutz"
            >{{ _("Privacy") }}</a
          >
        </div>
        <div
          class="col-md d-flex align-items-center justify-content-center p-2 text-nowrap"
        >
          {{ currentYear }} &ndash; &VeryThinSpace;
          <a
            class="link-light text-decoration-none d-inline"
            target="_blank"
            rel="noopener noreferrer"
            href="https://www.lbz.rwth-aachen.de/cms/LBZ/Das-Lehrerbildungszentrum/Geschaeftsstelle/~vcacl/MediaLab/"
            ><b>RWTH MediaLab</b></a
          >
        </div>
        <div class="nav col-md-2 justify-content-end p-2 ms-auto">
          {% if g.locales|length > 1 %}
            <a
              class="link-light text-decoration-none"
              role="button"
              onclick="change_langauge()"
              style="margin-right: 15px"
              >{{ 'de' if g.locale == 'en' else 'en' }}</a
            >
          {% endif %}
          <a
            class="link-light text-decoration-none"
            target="_blank"
            rel="noopener noreferrer"
            href="https://discord.gg/tXwkfcMyjK"
          >
            <img
              src="{{ url_for('static', filename='img/discord-mark-blue.svg') }}"
              alt="Discord"
              style="height: 25px; padding-right: 15px"
            />
          </a>
          <a
            class="link-light text-decoration-none"
            target="_blank"
            rel="noopener noreferrer"
            href="https://git.rwth-aachen.de/medialab/19squared"
          >
            <img
              src="{{ url_for('static', filename='img/gitlab-logo-500.svg') }}"
              alt="GitLab"
              style="height: 25px; padding-right: 15px"
            />
          </a>
          <a
            class="link-light text-decoration-none"
            target="_blank"
            rel="noopener noreferrer"
            href="https://git.rwth-aachen.de/medialab/19squared/-/tree/{{ VERSION }}"
          >
            v{{ VERSION }}
          </a>
        </div>
      </footer>
    </div>
    <script>
      function change_langauge() {
        var selectedLanguage =
          "{{ 'de' if request.cookies.get('language') == 'en' else 'en' }}";
        document.cookie = "language=" + selectedLanguage + "; path=/";
        if ("{{ current_user.is_authenticated }}" === "True") {
          $.ajax({
            url: '{{ url_for("home.set_language") }}',
            type: "PUT",
            headers: {
              "Content-Type": "application/json",
              Accept: "application/json",
            },
            data: JSON.stringify({
              language: selectedLanguage,
            }),
            success: function (result) {
              location.reload();
            },
            error: function (error) {
              console.log(error);
            },
          });
        } else {
          location.reload();
        }
      }
    </script>
  </body>
</html>

src/app/templates/error.html
{% extends "base.html" %} {% block title %}{{ status_code }}{% endblock %}
{% block content %}
  <main>
    <section class="d-flex align-items-center justify-content-center">
      <div class="container">
        <div class="row">
          <div
            class="col-12 text-center d-flex align-items-center justify-content-center"
          >
            <div>
              <h1 class="mt-5">{{ status_message }}</h1>
              <img src="https://http.cat/{{ status_code }}" />
              <script>
                console.error("{{ status_message }}");
              </script>
            </div>
          </div>
        </div>
      </div>
    </section>
  </main>
{% endblock content %}
{% block javascripts %}
{% endblock javascripts %}

src/app/templates/impressum.html
{% extends "base.html" %}
{% block content %}
  <div class="text">
    <a id="top" class="hiddenmark"></a>
    <h1>Impressum</h1>
    <h2>Herausgeberin</h2>
    <p>
      Rheinisch-Westfälische Technische Hochschule (RWTH) Aachen<br />Templergraben
      55<br />52062 Aachen (Hausanschrift)<br />52056 Aachen (Postanschrift)
    </p>
    <p>
      Telefon: +49 241 80 1<br />Telefax: +49 241 80 92312<br />E-Mail:
      impressum@rwth-aachen.de
    </p>
    <p>
      Die Rheinisch-Westfälische Technische Hochschule (RWTH) Aachen ist eine
      Körperschaft des öffentlichen Rechts. Sie wird durch den Rektor,
      Univ.-Prof. Dr. rer. nat. Dr. h.c. mult. Ulrich Rüdiger, vertreten.
    </p>
    <h2>Zuständige Aufsichtsbehörde</h2>
    <p>
      Ministerium für Kultur und Wissenschaft des Landes Nordrhein Westfalen,
      Völklinger Straße 49, 40221 Düsseldorf.
    </p>
    <h2>Umsatzsteuer-Identifikationsnummer</h2>
    <p>Gemäß § 27 a Umsatzsteuergesetz: DE 121689807</p>
    <h2>Inhaltliche Verantwortlichkeit</h2>
    <p>
      <span>Ansprechpartner:</span> Lars Bücken<br />
      <br />
      Telefon: +49 241 80 96425<br />
      E-Mail:
      <a class="email" href="mailto:webmaster@lbz.rwth-aachen.de"
        >webmaster@lbz.rwth-aachen.de</a
      >
      <br />
      <br />
      <span>Webmaster:</span> Lars Bücken<br />
      <br />
      Telefon: +49 241 80 96425<br />
      E-Mail:
      <a class="email" href="mailto:webmaster@lbz.rwth-aachen.de"
        >webmaster@lbz.rwth-aachen.de</a
      >
    </p>
    <p>
      Die Webseiten der Zentralen Hochschulverwaltung, der Zentralen
      Einrichtungen, der Gruppenvertretungen, der Institute, Lehrstühle sowie
      Lehr- und Forschungsgebiete werden von den von diesen beauftragten
      Webkoordinatorinnen und Webkoordinatoren beziehungsweise deren Webmastern
      eigenständig betreut. Details zu Fragen der Haftung sind in der
      <a class="internal" href="/datenschutz" target="_self"
        >Datenschutzerklärung</a
      >
      nachzulesen.
    </p>
  </div>
{% endblock content %}
{% block javascripts %}
{% endblock javascripts %}

src/app/templates/index.html
{% extends "base.html" %} {% block title %}Home{% endblock %}
{% block content %}
  <div class="jumbotron">
    <a class="navbar-brand" href="/view/demo">
      <div class="d-flex justify-content-center align-items-center">
        <img
          src="{{ url_for('static', filename='img/brand/logo5.png') }}"
          class="img-fluid z-2"
          style="height: 45vh"
          alt="19squared"
        />
        <video
          autoplay
          loop
          muted
          class="img-fluid position-absolute z-1"
          style="height: 8vh; margin-bottom: 18vh; margin-left: 13vh"
        >
          <source
            src="{{ url_for('static', filename='video/demo.mp4') }}"
            type="video/mp4"
          />
        </video>
      </div>
    </a>

    <h1 class="display-3" style="text-align: center">
      <b>19squared</b> - {{ _("Just more than 360") }}
    </h1>
    <p class="lead" style="text-align: center">
      {{ _("A web application for creating and experiencing interactive 360° tours in extended reality environments.") }}
    </p>
    <div class="d-flex justify-content-center align-items-center">
      <a href="/view/demo" target="_blank" class="btn btn-primary"
        >{{ _("View Demo Tour") }}</a
      >
    </div>
    <hr class="my-4" />
    <div style="text-align: center">
      <p class="lead">
        {{ _("You are currently not logged in. Please") }}
        <a href="{{ url_for('auth.register') }}">{{ _("register") }}</a>
        {{ _("or") }}
        <a href="{{ url_for('auth.login') }}">{{ _("login") }}</a>
        {{ _("with your existing") }}
        {{ _("credentials.") }}
      </p>
    </div>
  </div>
{% endblock %}